In [ ]:
lst = [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]
print("List ban đầu:", lst)
even_positions = lst[::2]
print("Các vị trí chẵn:", even_positions)
tpl = tuple(lst)
print("Tuple:", tpl)
d = {i: v for i, v in enumerate(lst)}
print("Dict:", d)
s = set(lst)
print("Set:", s)
removed = len(lst) - len(s)
print("Số phần tử bị loại trùng:", removed)

List ban đầu: [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]
Các vị trí chẵn: [1, 3, 5, 7, 9]
Tuple: (1, 2, 3, 2, 5, 1, 7, 9, 9, 4)
Dict: {0: 1, 1: 2, 2: 3, 3: 2, 4: 5, 5: 1, 6: 7, 7: 9, 8: 9, 9: 4}
Set: {1, 2, 3, 4, 5, 7, 9}
Số phần tử bị loại trùng: 3


In [5]:
# Bài 2
import json
with open("data.txt", "w", encoding="utf-8") as f:
    f.write("Dòng 1\n")
    f.write("Dòng 2\n")
    f.write("Dòng 3\n")
    f.write("Dòng 4\n")
    f.write("Dòng 5\n")

print("Đã tạo xong file data.txt")
print("\nNội dung file data.txt:")
with open("data.txt", "r", encoding="utf-8") as f:
    for line in f:
        print(line.strip())
student = {
    "name": "Nguyen Van A",
    "age": 20,
    "major": "Computer Science",
    "id": "SV001"
}
with open("student.json", "w", encoding="utf-8") as f:
    json.dump(student, f, ensure_ascii=False, indent=4)
print("\nĐã ghi vào student.json")
print("\nNội dung student.json:")
with open("student.json", "r", encoding="utf-8") as f:
    data = json.load(f)
    print(data)

Đã tạo xong file data.txt

Nội dung file data.txt:
Dòng 1
Dòng 2
Dòng 3
Dòng 4
Dòng 5

Đã ghi vào student.json

Nội dung student.json:
{'name': 'Nguyen Van A', 'age': 20, 'major': 'Computer Science', 'id': 'SV001'}


In [6]:
# Bài 3
import numpy as np

arr = np.arange(12).reshape(3, 4)
print("Mảng ban đầu:")
print(arr)

row2 = arr[1]
print("\nHàng 2:", row2)

col3 = arr[:, 2]
print("Cột 3:", col3)

sub = arr[1:3, 2:4]
print("Submatrix:\n", sub)

arr_float = arr.astype(np.float64)
print("\nDtype mới:", arr_float.dtype)

Mảng ban đầu:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Hàng 2: [4 5 6 7]
Cột 3: [ 2  6 10]
Submatrix:
 [[ 6  7]
 [10 11]]

Dtype mới: float64


In [7]:
# Bài 4
import pandas as pd

# Tạo Series điểm 5 sinh viên
score = pd.Series([7.5, 8.0, 6.5, 9.0, 8.5])

# Tạo DataFrame gồm name, age, score
data = {
    "name": ['An', 'Bình', 'Châu', 'Dũng', 'Hà'],
    "age": [20, 21, 22, 20, 23],
    "score": score
}
df = pd.DataFrame(data)

# In df.info()
print("df.info():")
print(df.info())

# In df.describe()
print("\ndf.describe():")
print(df.describe())

# Lọc sinh viên điểm ≥ 8
filtered = df[df["score"] >= 8]

print("\nSinh viên >= 8 điểm:")
print(filtered.values.tolist())


df.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   age     5 non-null      int64  
 2   score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes
None

df.describe():
            age     score
count   5.00000  5.000000
mean   21.20000  7.900000
std     1.30384  0.961769
min    20.00000  6.500000
25%    20.00000  7.500000
50%    21.00000  8.000000
75%    22.00000  8.500000
max    23.00000  9.000000

Sinh viên >= 8 điểm:
[['Bình', 21, 8.0], ['Dũng', 20, 9.0], ['Hà', 23, 8.5]]


In [ ]:
# Bài 5
import pandas as pd

# ============================
# 1) Tạo file students.csv
# ============================
students_data = """id,name
1,An
2,Binh
3,Chau
"""

with open("students.csv", "w", encoding="utf-8") as f:
    f.write(students_data)

# ============================
# 2) Tạo file scores.csv
# ============================
scores_data = """id,score
1,8
2,9
3,7
"""

with open("scores.csv", "w", encoding="utf-8") as f:
    f.write(scores_data)

# ============================
# 3) Đọc file bằng pandas
# ============================
students_df = pd.read_csv("students.csv")
scores_df = pd.read_csv("scores.csv")

# ============================
# 4) Merge theo id
# ============================
merged = pd.merge(students_df, scores_df, on="id")

# ============================
# 5) Tính min – max – mean cho từng sinh viên
# (Trường hợp thực tế mỗi sinh viên có nhiều điểm)
# ============================
report = merged.groupby(["id", "name"]).agg(
    score_min=("score", "min"),
    score_max=("score", "max"),
    score_mean=("score", "mean")
).reset_index()

print(report)

# ============================
# 6) Lưu vào report.csv
# ============================
report.to_csv("report.csv", index=False)


In [ ]:
# Bài 6
import numpy as np

# Tạo mảng a kích thước (4,1)
a = np.array([[1], [2], [3], [4]])
print("a =\n", a)

# Tạo mảng b kích thước (1,5)
b = np.array([[10, 20, 30, 40, 50]])
print("\nb =\n", b)

# Broadcasting tính a * b
result = a * b
print("\nKết quả a * b =\n", result)

# Áp dụng sqrt() và log()
sqrt_result = np.sqrt(result)
log_result = np.log(result)

print("\nsqrt(result) =\n", sqrt_result)
print("\nlog(result) =\n", log_result)

# Tính min, max, mean, std theo axis=1
min_vals = np.min(result, axis=1)
max_vals = np.max(result, axis=1)
mean_vals = np.mean(result, axis=1)
std_vals = np.std(result, axis=1)

print("\nMin theo axis=1 =", min_vals)
print("Max theo axis=1 =", max_vals)
print("Mean theo axis=1 =", mean_vals)
print("Std theo axis=1 =", std_vals)


In [ ]:
# Bài 7
import pandas as pd
import numpy as np

# ============================
# 1) Tạo DataFrame
# ============================
df = pd.DataFrame({
    "name": ["An", "Bình", "Châu", "Dũng"],
    "age": [20, np.nan, 22, 21],
    "score": [8.5, np.nan, 7.0, 9.0],
    "city": ["Hà Nội", "HCM", np.nan, "Hà Nội"]
})

print("Data gốc:")
print(df)

# ============================
# 2) Kiểm tra dữ liệu thiếu
# ============================
print("\nDữ liệu thiếu:")
print(df.isna())

# ============================
# 3) Điền dữ liệu thiếu
# ============================
df["age"] = df["age"].fillna(df["age"].mean())      # mean
df["score"] = df["score"].fillna(df["score"].median())  # median
df["city"] = df["city"].fillna("Unknown")           # Unknown

print("\nage_cleaned =", df["age"].tolist())
print("score_cleaned =", df["score"].tolist())
print("city_cleaned =", df["city"].tolist())

# ============================
# 4) Chuyển city → category
# ============================
df["city"] = df["city"].astype("category")

print("\ncity dtype =", df["city"].dtype)

# ============================
# 5) Tạo cột score_level bằng apply()
# ============================
def level(score):
    if score >= 8:
        return "Good"
    elif score >= 7:
        return "Average"
    return "Bad"

df["score_level"] = df["score"].apply(level)
print("\nscore_level =", df["score_level"].tolist())

# ============================

df["age_normalized"] = (df["age"] - df["age"].mean()) / df["age"].std()

print("\nage_normalized =", df["age_normalized"].tolist())


In [ ]:
# Bài 8
from pathlib import Path
from datetime import datetime
import json
import pandas as pd

# ==============================
# 1) Lấy toàn bộ file JSON
# ==============================
log_folder = Path("logs/")
json_files = list(log_folder.glob("*.json"))

records = []

# ==============================
# 2) Đọc từng file + lấy ngày từ tên
# ==============================
for file in json_files:
    # Ví dụ tên file: log_2025-05-21.json
    date_str = file.stem.split("_")[-1]  
    log_date = datetime.strptime(date_str, "%Y-%m-%d").date()

    # Đọc JSON
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Giả sử JSON có dạng:
    # {"user": "...", "action": "...", "duration": 12.5}
    record = {
        "date": log_date,
        "user": data.get("user"),
        "action": data.get("action"),
        "duration": data.get("duration", 0)
    }
    records.append(record)

# ==============================
# 3) Tạo DataFrame
# ==============================
df = pd.DataFrame(records)
print("DataFrame tổng hợp:")
print(df)

# ==============================
# 4) Tổng duration theo ngày
# ==============================
daily_report = df.groupby("date")["duration"].sum().reset_index()
print("\nBáo cáo theo ngày:")
print(daily_report)

# ==============================
# 5) Xuất ra CSV
# ==============================
daily_report.to_csv("daily_report.csv", index=False)
print("\nĐã tạo file daily_report.csv")
