In [52]:
"""
Tạo một mảng 1 chiều gồm các số nguyên từ 1 đến 10.
Kiểm tra kích thước (shape) và kiểu dữ liệu (dtype) của mảng vừa tạo.
Chuyển đổi mảng sang kiểu dữ liệu float và in kết quả.
Thực hiện với một mảng 2 chiều (3x3) chứa các số nguyên từ 1 đến 9 và kiểm tra các thuộc tính tương tự.
Input
Output
arr1 = np.arange(1, 11) 
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  
shape1 = (10,)
dtype1 = np.int32
shape2 = (3, 3)
dtype2 = np.int32
dtype_float = np.float32
"""
import numpy as np

arr1 = np.arange(1, 11)
print("arr1 =", arr1)

shape1 = arr1.shape
dtype1 = arr1.dtype
print("shape1 =", shape1)
print("dtype1 =", dtype1)

arr1_float = arr1.astype(np.float32)
dtype_float = arr1_float.dtype
print("dtype_float =", dtype_float)

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("arr2 =")
print(arr2)

shape2 = arr2.shape
dtype2 = arr2.dtype
print("shape2 =", shape2)
print("dtype2 =", dtype2)


arr1 = [ 1  2  3  4  5  6  7  8  9 10]
shape1 = (10,)
dtype1 = int64
dtype_float = float32
arr2 =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape2 = (3, 3)
dtype2 = int64


In [53]:
"""
Tạo một mảng 1 chiều từ 1 đến 10.
Dùng indexing để truy cập phần tử đầu tiên, phần tử cuối cùng và một phần tử ở giữa mảng.
Sử dụng slicing để trích xuất các phần tử từ vị trí 2 đến vị trí 5.
Thực hiện slicing trên một mảng 2 chiều (3x3) và trích xuất hàng thứ 2 và cột thứ 3.
Input
Output
arr1 = np.arange(1, 11)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
first_elem = 1
last_elem = 10
middle_elem = 6
sliced_arr = [3, 4, 5]
row2 = [4, 5, 6]
col3 = [3, 6, 9]
"""
import numpy as np

arr1 = np.arange(1, 11)

first_elem = arr1[0]
last_elem = arr1[-1]
middle_elem = arr1[len(arr1)//2]

sliced_arr = arr1[2:6]  

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row2 = arr2[1]

col3 = arr2[:, 2]

print("arr1 =", arr1)
print("arr2 =", arr2)

print("first_elem =", first_elem)
print("last_elem =", last_elem)
print("middle_elem =", middle_elem)

print("sliced_arr =", list(sliced_arr))
print("row2 =", list(row2))
print("col3 =", list(col3))



arr1 = [ 1  2  3  4  5  6  7  8  9 10]
arr2 = [[1 2 3]
 [4 5 6]
 [7 8 9]]
first_elem = 1
last_elem = 10
middle_elem = 6
sliced_arr = [np.int64(3), np.int64(4), np.int64(5), np.int64(6)]
row2 = [np.int64(4), np.int64(5), np.int64(6)]
col3 = [np.int64(3), np.int64(6), np.int64(9)]


In [63]:
"""
Tạo một mảng 2D kích thước 3x3 với các số ngẫu nhiên.
Tính toán các giá trị thống kê cơ bản: giá trị nhỏ nhất, giá trị lớn nhất, tổng, trung bình và độ lệch chuẩn.
Sử dụng tham số axis để tính các giá trị thống kê theo từng trục (hàng, cột).
Input
Output
 [[88, 35, 62],
 [11, 98, 34],
 [64, 24, 48]]
Min: 11
Max: 98
Sum: 402
Mean: 44.666666666666664
STD: 28.982830650276318
SumOfColumn: [163 157 144]
MeanOfColumn: [54.33333333 52.33333333 48.        ]
SumOfRow: [185 143 136]
MeanOfRow: [61.66666667 47.66666667 45.33333333]
"""
import numpy as np
import numpy as np

array_2d = np.random.randint(1, 100, (3, 3))
print(array_2d)

print(f"Min: {array_2d.min()}")
print(f"Max: {array_2d.max()}")
print(f"Sum: {array_2d.sum()}")
print(f"Mean: {array_2d.mean()}")
print(f"STD: {array_2d.std()}")

print(f"SumOfColumn: {array_2d.sum(axis=0)}")
print(f"MeanOfColumn: {array_2d.mean(axis=0)}")

print(f"SumOfRow: {array_2d.sum(axis=1)}")
print(f"MeanOfRow: {array_2d.mean(axis=1)}")


[[57 92 95]
 [96  5 41]
 [50 64 91]]
Min: 5
Max: 96
Sum: 591
Mean: 65.66666666666667
STD: 29.30301463444788
SumOfColumn: [203 161 227]
MeanOfColumn: [67.66666667 53.66666667 75.66666667]
SumOfRow: [244 142 205]
MeanOfRow: [81.33333333 47.33333333 68.33333333]


In [67]:
"""
Tạo một mảng 2D kích thước 3x3 với các giá trị ngẫu nhiên.
Tạo một mảng 1D có kích thước 3 và thực hiện phép cộng giữa mảng 2D và mảng 1D, áp dụng broadcasting.
Thực hiện phép trừ giữa mảng 2D và mảng có kích thước 1x3.
Kiểm tra kết quả và giải thích quá trình broadcasting.
Input
Output
 [[5 6 8]
 [7 2 4]
 [1 6 3]]
 [10 20 30]
Kết quả phép cộng A + B:
 [[15 26 38]
 [17 22 34]
 [11 26 33]]
Kết quả phép trừ A - B:
 [[ -5 -14 -22]
 [ -3 -18 -26]
 [ -9 -14 -27]]
"""
import numpy as np
array_1d = np.random.randint(1,101,(3))
array_2d = np.random.randint(1,101,(3,3))
print(array_1d)
print(array_2d)
print(f"Kết quả phép cộng:\n {np.add(array_1d,array_2d)}")
print(f"Kết quả phép trừ:\n {np.subtract(array_1d,array_2d)}")

[91 67 71]
[[75 22  1]
 [98 30 61]
 [97 53 86]]
Kết quả phép cộng:
 [[166  89  72]
 [189  97 132]
 [188 120 157]]
Kết quả phép trừ:
 [[ 16  45  70]
 [ -7  37  10]
 [ -6  14 -15]]


In [70]:
"""
Tạo một mảng 1D với các số ngẫu nhiên từ 1 đến 20.
Sử dụng vectơ hóa để tính bình phương và căn bậc hai của tất cả các phần tử trong mảng mà không cần vòng lặp.
Sử dụng hàm ufunc như np.add(), np.multiply(), np.sqrt() để thực hiện các phép toán giữa mảng và giá trị số.
Thực hiện phép tính với một mảng 2D và so sánh tốc độ với phương pháp vòng lặp thủ công.
"""
import numpy as np
import time
array_1d = np.random.randint(1,21,1)
print(f"Array_1d: {array_1d}")
print(f"Array_1d square: {array_1d**2}")
print(f"Array_1d square: {np.sqrt(array_1d)}")

print(f"Add 5: {np.add(array_1d, 5)}")
print(f"Multiply by 3: {np.multiply(array_1d, 3)}")
print(f"Sqrt (ufunc): {np.sqrt(array_1d)}")


array_2d = np.random.randint(1, 21, (500, 500))

start_vec = time.time()
result_vec = array_2d * 2 + 5
end_vec = time.time()

start_loop = time.time()
rows, cols = array_2d.shape
result_loop = np.zeros_like(array_2d)

for i in range(rows):
    for j in range(cols):
        result_loop[i, j] = array_2d[i, j] * 2 + 5

end_loop = time.time()

print("\n--- Speed Comparison ---")
print(f"Vectorized time: {end_vec - start_vec:.6f} sec")
print(f"Loop time:        {end_loop - start_loop:.6f} sec")


Array_1d: [8]
Array_1d square: [64]
Array_1d square: [2.82842712]
Add 5: [13]
Multiply by 3: [24]
Sqrt (ufunc): [2.82842712]

--- Speed Comparison ---
Vectorized time: 0.001782 sec
Loop time:        0.143400 sec


In [73]:
"""
Tạo một mảng 2D kích thước 4x4 với các giá trị ngẫu nhiên.
Tính tổng, trung bình, độ lệch chuẩn của mảng theo từng trục (axis=0, axis=1).
Giải thích sự khác biệt giữa tính toán theo trục cột và trục hàng.
Input
Output
[[3 7 4 5]
 [3 5 2 4]
 [6 3 9 7]
 [4 8 3 5]]
Tổng theo cột (axis=0): [16 23 18 21]
Trung bình theo cột (axis=0): [4.   5.75 4.5  5.25]
Độ lệch chuẩn theo cột (axis=0): [1.11803399 2.05350477 2.75947274 1.11803399]
Tổng theo hàng (axis=1): [19 14 25 20]
Trung bình theo hàng (axis=1): [4.75 3.5  6.25 5.  ]
Độ lệch chuẩn theo hàng (axis=1): [1.11803399 1.11803399 2.5        1.11803399]
"""
import numpy as np

arr_2d = np.random.randint(1, 11, (4, 4))
print(arr_2d)

print(f"Tổng theo cột (axis=0): {arr_2d.sum(axis=0)}")
print(f"Trung bình theo cột (axis=0): {arr_2d.mean(axis=0)}")
print(f"Độ lệch chuẩn theo cột (axis=0): {arr_2d.std(axis=0)}")

print(f"Tổng theo hàng (axis=1): {arr_2d.sum(axis=1)}")
print(f"Trung bình theo hàng (axis=1): {arr_2d.mean(axis=1)}")
print(f"Độ lệch chuẩn theo hàng (axis=1): {arr_2d.std(axis=1)}")



[[3 6 6 5]
 [5 6 7 2]
 [4 9 1 7]
 [8 1 1 5]]
Tổng theo cột (axis=0): [20 22 15 19]
Trung bình theo cột (axis=0): [5.   5.5  3.75 4.75]
Độ lệch chuẩn theo cột (axis=0): [1.87082869 2.87228132 2.77263413 1.78535711]
Tổng theo hàng (axis=1): [20 20 21 15]
Trung bình theo hàng (axis=1): [5.   5.   5.25 3.75]
Độ lệch chuẩn theo hàng (axis=1): [1.22474487 1.87082869 3.03108891 2.94745653]


In [ ]:
"""
Tạo một mảng 2D kích thước 5x5 với các giá trị ngẫu nhiên.
Tạo một mảng 1D kích thước 5 và thực hiện các phép toán với broadcasting (cộng, trừ) giữa mảng 2D và mảng 1D.
Áp dụng các hàm ufunc như np.sqrt(), np.add(),.. vào mảng 2D.
Đo tốc độ thực thi của việc sử dụng broadcasting và ufunc và so sánh với vòng lặp truyền thống.
Input
Output
 [[ 8 12 14  6  4]
 [18 13  2  2 12]
 [ 6 18  5 10 10]
 [ 9  2  4 12 12]
 [ 2  3  2 17  3]]
 [10 20 30 40 50]
Kết quả cộng (broadcasting):
 [[18 32 44 46 54]
 [28 33 32 42 62]
 [16 38 35 50 60]
 [19 22 34 52 62]
 [12 23 32 57 53]]
Kết quả trừ (broadcasting):
 [[ -2  -8 -16 -34 -46]
 [  8  -7 -28 -38 -38]
 [ -4  -2 -25 -30 -40]
 [ -1 -18 -26 -28 -38]
 [ -8 -17 -28 -23 -47]]
Kết quả căn bậc hai (ufunc):
 [[2.82842712 3.46410162 3.74165739 2.44948974 2.        ]
 [4.24264069 3.60555128 1.41421356 1.41421356 3.46410162]
 [2.44948974 4.24264069 2.23606798 3.16227766 3.16227766]
 [3.        1.41421356 2.        3.46410162 3.46410162]
 [1.41421356 1.73205081 1.41421356 4.12310563 1.73205081]]
Kết quả cộng 5 vào mảng (ufunc):
 [[13 17 19 11  9]
 [23 18  7  7 17]
 [11 23 10 15 15]
 [14  7  9 17 17]
 [ 7  8  7 22  8]]
Thời gian thực thi vòng lặp thủ công: 0.001234 giây
"""
import numpy as np
import time

# -------------------------------
# 1. Tạo mảng 2D và 1D
# -------------------------------
arr_2d = np.random.randint(1, 21, (5, 5))
arr_1d = np.random.randint(10, 60, 5)

print(arr_2d)
print(arr_1d)

# -------------------------------
# 2. Broadcasting (cộng, trừ)
# -------------------------------
add_result = arr_2d + arr_1d
sub_result = arr_2d - arr_1d

print("Kết quả cộng (broadcasting):")
print(add_result)

print("Kết quả trừ (broadcasting):")
print(sub_result)

# -------------------------------
# 3. Ufunc: sqrt, add
# -------------------------------
sqrt_result = np.sqrt(arr_2d)
add5_result = np.add(arr_2d, 5)

print("Kết quả căn bậc hai (ufunc):")
print(sqrt_result)

print("Kết quả cộng 5 vào mảng (ufunc):")
print(add5_result)

# -------------------------------
# 4. So sánh tốc độ: broadcasting vs loop
# -------------------------------

# Broadcasting
start_bc = time.time()
bc_result = arr_2d + arr_1d
end_bc = time.time()
bc_time = end_bc - start_bc

# Vòng lặp thủ công
start_loop = time.time()
loop_result = np.zeros_like(arr_2d)

for i in range(arr_2d.shape[0]):
    for j in range(arr_2d.shape[1]):
        loop_result[i, j] = arr_2d[i, j] + arr_1d[j]

end_loop = time.time()
loop_time = end_loop - start_loop

print(f"Thời gian thực thi broadcasting: {bc_time:.6f} giây")
print(f"Thời gian thực thi vòng lặp thủ công: {loop_time:.6f} giây")

In [ ]:
"""
Tạo một ma trận vuông 3x3 với các giá trị ngẫu nhiên.
Tính ma trận nghịch đảo của ma trận vừa tạo.
Tính giá trị riêng và véc tơ riêng của ma trận.
So sánh kết quả giữa ma trận gốc và ma trận nghịch đảo.
Input
Output
[[6 9 7]
 [2 1 5]
 [7 8 3]]
Ma trận nghịch đảo:
 [[ 0.52941176 -0.23529412 -0.29411765]
 [-0.29411765  0.41176471 -0.05882353]
 [-0.05882353 -0.17647059  0.29411765]]
Giá trị riêng của ma trận: [15.67207479  0.27335687  -2.94543166]
Véc tơ riêng của ma trận:
 [[ 0.58528917 -0.3277603  -0.50732504]
 [ 0.72147434 -0.26197579  0.76096577]
 [ 0.36829758  0.90447319 -0.40544259]]
"""
import numpy as np

# 1. Tạo ma trận vuông 3x3 với giá trị ngẫu nhiên 1→10
A = np.random.randint(1, 11, (3, 3))
print(A)

# 2. Tính ma trận nghịch đảo
A_inv = np.linalg.inv(A)
print("Ma trận nghịch đảo:")
print(A_inv)

# 3. Tính giá trị riêng và véc tơ riêng
eigen_values, eigen_vectors = np.linalg.eig(A)

print("Giá trị riêng của ma trận:")
print(eigen_values)

print("Véc tơ riêng của ma trận:")
print(eigen_vectors)


In [ ]:
import numpy as np
arr_1d = np.array([1,2,3])
# print(arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
# print(arr_2d)

# np.zeros((2,3))
# np.ones((2,3))
# np.arange(0,10,2)
# np.eye(3,3)

# arr_float = np.array([1.7,2.8,3.9])
# print(f"{arr_float.astype(int)}")
# print(f"{arr_float.astype(str)}")

# print(arr_1d[::-1])
# print(arr_2d[:,1])

# print(arr_1d[(arr_1d>7) & (arr_1d<9)])
# print(arr_2d[arr_2d > 4])
# C = arr_1d + arr_2d
# print(C)
# print(arr_1d**2)
print(np.subtract(arr_1d,array_2d))


[[ 0  0  0]
 [-3 -3 -3]]
